<?
/*
	- Code Box Body
	This is the main body of the code box that outputs the codes/scripts
*/

//Check if the contents has been set
$ready = is_null(static::$code);

?>
<div class="codeviewer" data-selected="">
	<div class="codeviewer-header">
		<?
		/*
			- Header
			Outputs the array of file extensions in use to select the script/code to display.
			This is automatically generated by the files provided.
		*/
		?>
		<ul>
			<?
			
			if (!$ready) {
				foreach(static::$code as $ext => $code) {
				?>
				<li class="selected" data-lang="<?= $ext ?>"><?= strtoupper($ext) ?></li>
				<?
				}
			}
			else {
				echo "<li><i>No codes</i></li>";
			}
			
			?>
		</ul>
	</div>
	<?
	
	if (!$ready) { //Display only if the codes have been set
	
	foreach(static::$code as $codeLang => $codeStr) {
	?>
	<div class="codeviewer-body" data-lang="<?= $codeLang ?>" style="<? if (!isset($first)) {$first=false;} else {echo "display:none;";} ?>">
		<div class="codeviewer-no">
			<?
			// -- LINE COUNT -- //
			
			//Run through each number individually
			foreach($codeStr as $lineNo => $line) {
				//Output
				echo "<p>$lineNo</p>";
			}
			?>
		</div>
		<div class="codeviewer-code">
			<?
			
			// -- OUTPUT CODE -- //
			
			//Check for content. Fail if the file is not found, or empty file.
			if ($codeStr != "") {
				//Output code by individual lines
				foreach($codeStr as $lineNo => $line) {
					//Purify
					$line = htmlentities($line);
					//Output
					echo "<p>$line</p>";
				}
			}
			else { //Error
				echo "File not found";
			}
			
			?>
		</div>
	</div>
	<?
	}
	}
	
	?>
</div>
